In [2]:
#p1
try:
    import Productcheck

    def buy(product, num, price):
        pr=int(num)*int(price)
        if Productcheck.check(product,num):
            print('You bought %s and spent %d'%(product, pr))
        else:
            print('Sorry! We are out of this product.')

    def main():
        product = input("Choose a product: ")
        num = input("Quantity: ")
        price = input("Price: ")
        buy(product, num, price)

    if __name__ == '__main__':
        main()
    
except ModuleNotFoundError:
    print('No such module')

No such module


In [3]:
#p2
def div(x, y):
    assert y!=0, 'Can\'t divide'
    return x/y
div(540,0)

AssertionError: Can't divide

In [4]:
#p3

def example_func(my_list:list):
    try:
        my_sum = 0
        sum_of_pairs = []
        
        for i in range(len(my_list)):
            sum_of_pairs.append(my_list[i] + my_list[i+1])
        
       # print("SumOfPairs = ", sum_of_pairs)
    
    except IndexError:
        print('Index out of range')

    finally:
        print("SumOfPairs = ", sum_of_pairs)

In [ ]:
l1 = [12,54,87,96,74]
l2 = [1,2,3]
l3=[]
example_func(l2)

In [7]:
#p4

def UpperContent(fileName):
    try: 
        myfile = open(fileName, 'r')
        for line in myfile:
            print(line.upper())
        myfile.close()
    except FileNotFoundError:
        print('No such file or directory')
    except Exception as e:
        print(e)

In [8]:
UpperContent('article.txt')

1

COMPANIES THAT FIRST FACED THE OUTBREAK 

IN CHINA ARE USING THEIR EARLY EXPERIENCES 

TO FORM A BLUEPRINT FOR THE FUTURE OF GLOBAL BUSINESS.


In [9]:
import numpy as np

In [10]:
#p5 

a = np.random.randint(1,11,(3,5))
a

array([[ 8,  9,  2,  4,  4],
       [10,  4,  9,  6,  9],
       [ 9, 10,  9,  4,  4]])

In [11]:
#p6

a = np.zeros(10)
a[5]= 3
print(a)

[0. 0. 0. 0. 0. 3. 0. 0. 0. 0.]


In [12]:
#p7

a = np.arange(3,15)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
#p8

a = np.array([1, 3, 5, 2, 4, 5])
print(a.reshape(3,2))
print(a.reshape(2,3))
a

[[1 3]
 [5 2]
 [4 5]]
[[1 3 5]
 [2 4 5]]


array([1, 3, 5, 2, 4, 5])

In [14]:
#p9

def func_1(a):
    while np.mean(a)>5:
        a = np.divide(a,2)
    else:
        print(a)


In [15]:
m= np.array([10,2,12,24,8])
func_1(m)

[2.5 0.5 3.  6.  2. ]


In [16]:
#p10
def func_2(b):
    print(b,'\n')
    for x in range(b.shape[1]):
        print(b[...,x])


In [17]:
n = np.random.randint(1,11,(5,4))
func_2(n)

[[ 5  4  4  7]
 [10  1  3  6]
 [ 4  5  5 10]
 [ 6  4  3  4]
 [ 6  4  4  4]] 

[ 5 10  4  6  6]
[4 1 5 4 4]
[4 3 5 3 4]
[ 7  6 10  4  4]


In [18]:
def func_3(b):
    print(b,'\n')
    for x in range(b.shape[0]):
        print(b[x,...])


In [19]:
n = np.random.randint(1,11,(5,4))
func_3(n)

[[ 9  6  3  7]
 [ 5  3  5  4]
 [ 6  4  3  9]
 [ 4  1 10  9]
 [10  4  3  7]] 

[9 6 3 7]
[5 3 5 4]
[6 4 3 9]
[ 4  1 10  9]
[10  4  3  7]
